// Auto-generated by Tegaki. Do not edit manually.
import fontUrl from './dancing-script.ttf' with { type: 'url' };
import glyphData from './glyphData.json' with { type: 'json' };

const bundle = {
  version: 0,
  family: 'Dancing Script Tegaki 3dc76002',
  lineCap: 'round',
  fontUrl,
  fontFaceCSS: `@font-face { font-family: 'Dancing Script Tegaki 3dc76002'; src: url(${fontUrl}); }`,
  unitsPerEm: 1000,
  ascender: 920,
  descender: -280,
  glyphData,
} as const;

export default bundle;
